---
- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes

- name: copy plugins
  copy:
    src=plugins/
    dest=/etc/sensu/plugins/
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0750

- name: copy cfg templates
  template:
    src="{{item}}.json.j2"
    dest="/etc/sensu/conf.d/{{item}}.json"
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0640
    backup=yes
  with_items:
    - client
    - redis
    - transport
  notify: service restart sensu-client
