---

- name: client | enable sensu-client to survive reboot
  service:
    name=sensu-client
    enabled=yes

- name: client | copy plugins
  copy:
    src=plugins/{{item}}
    dest=/etc/sensu/plugins/{{item}}
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode="0750"
  with_items: sensu_client_plugins

- name: client | copy extra plugins
  copy:
    src=plugins/{{item}}
    dest=/etc/sensu/plugins/{{item}}
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode="0750"
  with_items: sensu_client_plugins_extra

- name: client | client.json template
  template:
    src: "client.json.j2"
    dest: "/etc/sensu/conf.d/client.json"
    owner: "{{sensu_user}}"
    group: "{{sensu_group}}"
    mode: "0640"
    backup: yes
  notify: service restart sensu-client

- name: client | transport.json template
  template:
    src: "transport.json.j2"
    dest: "/etc/sensu/conf.d/transport.json"
    owner: "{{sensu_user}}"
    group: "{{sensu_group}}"
    mode: "0640"
    backup: yes
  when: sensu_transport == "redis"
  notify: service restart sensu-client

- name: client | redis.json template
  template:
    src: "redis.json.j2"
    dest: "/etc/sensu/conf.d/redis.json"
    owner: "{{sensu_user}}"
    group: "{{sensu_group}}"
    mode: "0640"
    backup: yes
  when: sensu_transport == "redis"
  notify: service restart sensu-client

- name: client | checks.json template
  template:
    src: "checks.json.j2"
    dest: "/etc/sensu/conf.d/{{item.name}}.json"
    owner: "{{sensu_user}}"
    group: "{{sensu_group}}"
    mode: "0640"
  with_items: sensu_checks
  notify: service restart sensu-client

