---

- name: common | application defaults
  template:
    src=default-sensu.j2
    dest=/etc/default/sensu
    owner=root
    group=root
    mode=0644
  notify:
    - service restart sensu-server
    - service restart sensu-client

- name: common | create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0750
    state=directory
  when: sensu_transport == "rabbitmq" and not sensu_server_rabbitmq_insecure

- name: common | install ssl certificate and key
  copy:
    content: "{{item.content}}"
    dest: "/etc/sensu/ssl/{{item.filename}}"
    owner: "{{sensu_user}}"
    group: "{{sensu_group}}"
    mode: 0640
    backup: yes
  with_items: sensu_ssl_certs
  when: sensu_transport == "rabbitmq" and not sensu_server_rabbitmq_insecure
  notify:
    - service restart sensu-server
    - service restart sensu-client

- name: common | generate rabbitmq.json
  template:
    src=rabbitmq.json.j2
    dest=/etc/sensu/conf.d/rabbitmq.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  when: sensu_transport == "rabbitmq"
  notify:
    - service restart sensu-server
    - service restart sensu-client

