---
- include: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: set which Ruby to use
  lineinfile:
    dest=/etc/default/sensu
    regexp=^EMBEDDED_RUBY=
    line=EMBEDDED_RUBY={{ sensu_embedded_ruby }}

- name: set which user to use
  lineinfile:
    dest=/etc/default/sensu
    regexp=^USER=
    line=USER={{ sensu_user }}

- name: create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0750
    state=directory
  when: sensu_transport == "rabbitmq" and not sensu_server_rabbitmq_insecure

- name: install ssl certificate and key
  copy:
    src={{ item }}
    dest=/etc/sensu/ssl/{{ item }}
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0640
    backup=yes
  with_items:
    - "{{ sensu_cert_file_name }}"
    - "{{ sensu_key_file_name }}"
  when: sensu_transport == "rabbitmq" and not sensu_server_rabbitmq_insecure
  notify:
    - service restart sensu-server
    - service restart sensu-client

- name: generate rabbitmq.json
  template:
    src=rabbitmq.json.j2
    dest=/etc/sensu/conf.d/rabbitmq.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  when: sensu_transport == "rabbitmq"
  notify:
    - service restart sensu-server
    - service restart sensu-client
