---
# tasks file for sensu

- include: common.yml

- include: server.yml
  when: sensu_server

- include: uchiwa.yml
  when: sensu_server and sensu_uchiwa

- include: client.yml
  when: sensu_client

