---

- name: setup | add repo
  template:
    src: sensu.repo.j2
    dest: /etc/yum.repos.d/sensu.repo
    mode: "0644"

- name: setup | install pkg
  yum:
    pkg={{sensu_pkg_name}}
    state={{sensu_pkg_state}}
    enablerepo=sensu

- name: install custom gems
  command: "/opt/sensu/embedded/bin/gem install {{item.name}} --no-rdoc --no-ri -v {{item.version}}"
  args:
    creates: /opt/sensu/embedded/lib/ruby/gems/2.0.0/specifications/{{item.name}}-{{item.version}}.gemspec
  with_items: sensu_custom_gems

