---

- name: setup | add repo
  template:
    src: sensu.repo.j2
    dest: /etc/yum.repos.d/sensu.repo
    mode: "0644"

- name: setup | install pkg
  yum:
    pkg={{sensu_pkg_name}}
    state={{sensu_pkg_state}}
    enablerepo=sensu

- name: setup | install dev tools
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - gcc
    - mysql-devel
    - ruby-devel
    - rubygems

- name: setup | copy gems
  copy:
    src: "files/{{item.name}}-{{item.version}}.gem"
    dest: "/tmp"
  with_items: "{{sensu_custom_gems}}"
  when: item.source is defined and item.source == "files"

- name: setup | register gem version
  shell: "/opt/sensu/embedded/bin/ruby -v | cut -b6-8"
  register: st

- name: setup | install custom gems
  command: "/opt/sensu/embedded/bin/gem install {{item.name}} --no-rdoc --no-ri -v {{item.version}}"
  args:
    creates: /opt/sensu/embedded/lib/ruby/gems/{{st.stdout}}.0/specifications/{{item.name}}-{{item.version}}.gemspec
    chdir: /tmp
  with_items: "{{sensu_custom_gems}}"
