---

# this requires libselinux-python
- name: add repo
  template:
    src: sensu.repo.j2
    dest: /etc/yum.repos.d/sensu.repo
    mode: "0644"

- name: install pkg
  yum:
    pkg={{sensu_pkg_name}}
    state={{sensu_pkg_state}}
    enablerepo=sensu
