---
# handlers file for sensu
- name: service restart sensu-server
  service: name=sensu-{{ item }} state=restarted
  with_items:
    - server
    - api
  when: sensu_server

- name: service restart sensu-client
  service: name=sensu-client state=restarted
  when: sensu_client

- name: service restart uchiwa
  service: name=uchiwa state=restarted
  when: sensu_uchiwa
